# Generated by Django 3.0.7 on 2022-04-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab_task_summary',
            old_name='equpments',
            new_name='equipments',
        ),
    ]
